# By Yule

# 这是 Live Photo Tools 的配置文件
# 你可以在此个性化部分设置
# 欲了解如何填写，见 GitHub 或 README.md

# <----- 基础设置 ----->

# 默认系统设置。你需要处理什么系统的动态照片就填什么，请区分大小写。默认: null (未设置)
# [MIUI/HyperOS] / [ColorOS]
"OS": null

# 工具释放目录。在未 Root 的设备上请使用 [HOME], 工具会被释放到终端软件的私有目录，这可以帮助你正确地释放文件；在已 Root 的设备，我们建议您使用 [/data/local/tmp]。为了良好的转义，请始终不要删除双引号。
# [目录]
"ToolTmp": "HOME"